name: Setup node and yarn

description: Action to setup Node.js, yarn and install dependencies

inputs:
  CACHE_FILE_NAME:
    description: A string to differentiate the cache creation for whole repo or specific app
    required: true
  TBLX_NPM_ARTIFACT_TOKEN:
    description: Artifactory technical user token
    required: true
  TBLX_NPM_ARTIFACT_USERNAME:
    description: Artifactory technical user username
    required: true
  NODE_VERSION:
    description: The node version to be installed
    required: false
    default: '22'
  NPM_TOKEN:
    description: NPM token for publishing to npmjs.org
    required: false

runs:
  using: composite
  steps:
    # Install Node
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}

    # Setup npm authentication if token is provided
    - name: Setup npm authentication
      if: inputs.NPM_TOKEN != ''
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" > .npmrc

    # As we're using self-hosted runners we need to install yarn
    - name: Install yarn
      shell: bash
      run: |
        npm install -g yarn
        npm install turbo --global

    # Create a cache from yarn.lock so we can skip the dependency installation if needed
    - id: cache-node_modules
      uses: actions/cache@v4
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          ~/.yarn
          **/node_modules
        # An explicit key for restoring and saving the cache
        key: ${{ inputs.CACHE_FILE_NAME }}-node-v${{ inputs.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}-${{ hashFiles('packages/dt-dds-react/package.json') }}
        restore-keys: |
          ${{ inputs.CACHE_FILE_NAME }}-node-v${{ inputs.NODE_VERSION }}-deps-

    # Install dependencies if there isn't a hit on the cache
    - name: Install dependencies
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn --frozen-lockfile
