import { radius } from './radius';

export const shape = {
  // Existing shapes
  button: radius['none'],
  checkbox: radius['none'],
  modal: radius['none'],
  emptyState: radius['none'],
  dropdown: radius['none'],
  message: radius['none'],
  toast: radius['none'],
  tooltip: radius['none'],
  progressbar: radius['none'],
  accordion: radius['none'],
  formField: radius['none'],
  segmentedControl: radius['none'],
  // New shapes from JSON
  avatar: radius['full'],
  badge: radius['full'],
  card: radius['none'],
  container: radius['none'],
  datepicker: radius['none'],
  drawer: radius['none'],
  timepicker: radius['none'],
  pagination: radius['none'],
  radioButton: radius['full'],
  tab: radius['none'],
  toggle: radius['l'],
  tagRounded: radius['m'],
  tagSquared: radius['none'],
  switch: radius['none'],
  definitionList: radius['none'],
  header: radius['none'],
  navigationMenu: radius['none'],
  option: radius['none'],
  kpiCard: radius['none'],
  footer: radius['none'],
  slider: radius['s'],
  skeleton: radius['none'],
};
