import { CustomTheme as Theme } from '../../types';

export const shape: Theme['shape'] = {
  button: '0px',
  checkbox: '0px',
  modal: '0px',
  emptyState: '0px',
  dropdown: '0px',
  message: '0px',
  toast: '0px',
  tooltip: '0px',
  progressbar: '0px',
  accordion: '0px',
  formField: '0px',
  segmentedControl: '0px',
  avatar: '100px',
  badge: '100px',
  card: '0px',
  container: '0px',
  datepicker: '0px',
  drawer: '0px',
  timepicker: '0px',
  pagination: '0px',
  radioButton: '100px',
  tab: '0px',
  toggle: '56px',
  tagRounded: '16px',
  tagSquared: '0px',
  switch: '0px',
  definitionList: '0px',
  header: '0px',
  navigationMenu: '0px',
  option: '0px',
  kpiCard: '0px',
  footer: '0px',
  slider: '8px',
  skeleton: '0px',
} as const;
