name: Theme Generation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/themes/src/tokens/**/*.json'
      - 'packages/themes/src/utils/theme-generator/**/*'
      - 'packages/themes/src/types/theme.ts'
      - 'packages/themes/package.json'

jobs:
  generate-themes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node and yarn
        uses: './.github/actions/yarn-node-install'
        with:
          CACHE_FILE_NAME: 'global'

      - name: Generate themes
        id: generate
        run: |
          echo "🎨 Starting theme generation..."
          yarn build:theme
          echo "✅ Theme generation completed"
        working-directory: packages/themes
        continue-on-error: true

      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Generated theme files have changes"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes in generated theme files"
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changes == 'true' && steps.generate.outcome == 'success'
        run: |
          git config --local user.email "dt-ui@daimlertruck.com"
          git config --local user.name "dt-ui"
          git add packages/themes/src/themes/
          git commit -m "feat: auto-generate themes from tokens"

          This commit was automatically generated by 
          the theme generation workflow.

          Changes detected in token files:
          ${{ github.event.pull_request.title }}

          Generated theme files have been updated 
          to reflect the latest token changes.

          Triggered by: ${{ github.event.pull_request.html_url }}"

      - name: Push changes
        if: steps.check-changes.outputs.changes == 'true' && steps.generate.outcome == 'success'
        run: git push

      - name: Comment on PR
        if: steps.generate.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **Theme Generation Failed**
              
              The theme generation process encountered an error. Please check the workflow logs for details.
              
              This usually happens when:
              - Token files have syntax errors
              - Required tokens are missing
              - Theme validation fails
              
              Please review the token files and try again.`
            })

      - name: Comment on PR - Success
        if: steps.check-changes.outputs.changes == 'true' && steps.generate.outcome == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Theme Generation Successful**
              
              The theme generation process completed successfully and the generated theme files have been committed to this PR.
              
              The following theme files were updated:
              - \`packages/themes/src/themes/\`
              
              All themes have been regenerated based on the latest token changes.`
            })

      - name: Comment on PR - No Changes
        if: steps.check-changes.outputs.changes == 'false' && steps.generate.outcome == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ℹ️ **Theme Generation - No Changes**
              
              The theme generation process completed successfully, but no changes were detected in the generated theme files.
              
              This means the token changes in this PR don't affect the theme generation output.`
            })
